import React from 'react'
import Head from 'next/head'
import SideBar from '../components/SideBar'
import Songs from '../src/mock_data.json'
import SongsList from '../components/SongsList'
import Search from '../components/Search'

export default function dashboard() {
  const ListSongs = Songs.song_playlist.data
  return (
    <div className='min-h-screen max-w-screen'>
      <Head>
        <title>Dashboard | TheLorry Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-black/90 h-full flex '>
        <div className="w-1/5">
           <SideBar /> 
        </div>
        
        <div className=' w-4/5 p-3 lg:p-16'>
          <div className="lg:flex justify-between">
            <div>
              <h1 className='text-white text-4xl'>My music list</h1>
              <h2 className='text-white pt-3'>My recent search list</h2>
            </div>

            <div className='w-full lg:w-1/4 pt-3 lg:pt-0'>
              <Search />
            </div>
          </div>

          <div className='space-y-4 pt-6'>
            {
              ListSongs.map((item) => (
                <SongsList 
                  key={item.id}
                  title={item.song_name}
                  band={item.band_name}
                  year={item.year}
                  downloaded={item.downloaded}
                />
              ))
            }
          </div>
            
        </div>
      </div>
    </div>
  )
}
