import Head from 'next/head'
import Image from 'next/image'
import SignIn from '../components/SignIn'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>TheLorry Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-full flex items-center justify-center'>
        <div className='h-full w-2/5 absolute bg-gradient-to-t from-red-500 via-red-600 to-red-700 left-0 flex items-center justify-center'>
          <Image
                alt=''
                src='/music-hero 1.svg'
                layout="fill"
            />
        </div>

        <div className='bg-white w-11/12 lg:w-1/3 h-[700px] rounded-lg shadow-lg shadow-red-500/30 p-8 z-10'>
          <SignIn />
        </div>
      </div>
    </div>
  )
}
