import React from 'react'
import Head from 'next/head'
import { SignUp } from '../components/SignUp'

export default function signup() {
  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>Sign Up | TheLorry Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-full flex items-center justify-center'>
        <div className='h-full w-2/5 absolute bg-gradient-to-t from-red-500 via-red-600 to-red-700 left-0'>
        </div>

        <div className='bg-white w-11/12 lg:w-1/3 h-[700px] rounded-lg shadow-lg shadow-red-500/30 p-8 z-10 overflow-auto'>
            <SignUp />
        </div>
      </div>
    </div>
  )
}
